// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6ggiMbq-1CCcXX3r8YaHU0ox1Roa9AWY',
    appId: '1:905789855925:web:bdd87624c7901d892ec6fc',
    messagingSenderId: '905789855925',
    projectId: 'nutrition-app-d28c9',
    authDomain: 'nutrition-app-d28c9.firebaseapp.com',
    storageBucket: 'nutrition-app-d28c9.firebasestorage.app',
    measurementId: 'G-TEMQ2XXGFF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeTp0YOewlPqUeA8DnYDxgfUQ1dt2201Q',
    appId: '1:905789855925:android:38b87f83d72854eb2ec6fc',
    messagingSenderId: '905789855925',
    projectId: 'nutrition-app-d28c9',
    storageBucket: 'nutrition-app-d28c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApTeCl2mECUkmF_qrCBV0nbrWpQRMPsG4',
    appId: '1:905789855925:ios:62fa967fa0dede1b2ec6fc',
    messagingSenderId: '905789855925',
    projectId: 'nutrition-app-d28c9',
    storageBucket: 'nutrition-app-d28c9.firebasestorage.app',
    iosBundleId: 'com.example.nutribite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApTeCl2mECUkmF_qrCBV0nbrWpQRMPsG4',
    appId: '1:905789855925:ios:62fa967fa0dede1b2ec6fc',
    messagingSenderId: '905789855925',
    projectId: 'nutrition-app-d28c9',
    storageBucket: 'nutrition-app-d28c9.firebasestorage.app',
    iosBundleId: 'com.example.nutribite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6ggiMbq-1CCcXX3r8YaHU0ox1Roa9AWY',
    appId: '1:905789855925:web:a8642a2947f5ea1a2ec6fc',
    messagingSenderId: '905789855925',
    projectId: 'nutrition-app-d28c9',
    authDomain: 'nutrition-app-d28c9.firebaseapp.com',
    storageBucket: 'nutrition-app-d28c9.firebasestorage.app',
    measurementId: 'G-P54Y9MH1GN',
  );
}
